name: FoxBukkit
main: de.doridian.foxbukkit.core.FoxBukkit
version: 1.0.0
depend: [WorldEdit]
softdepend: [dynmap, LogBlock, RemoteEntities]
commands:
    fb:
        description: Runs any FoxBukkit command (used for console)
        permission: foxbukkit.no_one_has_this_ever
        usage: /<command>